/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlockedSchema extends BaseModel {
  static $columns = ['alanyaId', 'createdAt', 'dateBlock', 'idBlock', 'idCallerBlock', 'updatedAt'] as const
  $columns = BlockedSchema.$columns
  @column()
  declare alanyaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare dateBlock: DateTime
  @column({ isPrimary: true })
  declare idBlock: number
  @column()
  declare idCallerBlock: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CallHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'duree', 'idCall', 'idCaller', 'idReceiver', 'startTime', 'status', 'type', 'updatedAt'] as const
  $columns = CallHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duree: number | null
  @column({ isPrimary: true })
  declare idCall: number
  @column()
  declare idCaller: number | null
  @column()
  declare idReceiver: number | null
  @column.dateTime()
  declare startTime: DateTime | null
  @column()
  declare status: number | null
  @column()
  declare type: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConversationSchema extends BaseModel {
  static $columns = ['conversId', 'createdAt', 'groupName', 'groupPhoto', 'isArchived', 'isGroup', 'isPinned', 'lastMessage', 'lastMessageAt', 'participantId', 'unreadCount', 'updatedAt'] as const
  $columns = ConversationSchema.$columns
  @column({ isPrimary: true })
  declare conversId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupName: string | null
  @column()
  declare groupPhoto: string | null
  @column()
  declare isArchived: boolean | null
  @column()
  declare isGroup: boolean | null
  @column()
  declare isPinned: boolean | null
  @column()
  declare lastMessage: string | null
  @column.dateTime()
  declare lastMessageAt: DateTime | null
  @column()
  declare participantId: number | null
  @column()
  declare unreadCount: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GroupParticipantSchema extends BaseModel {
  static $columns = ['conversId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = GroupParticipantSchema.$columns
  @column()
  declare conversId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class MeetingSchema extends BaseModel {
  static $columns = ['createdAt', 'duree', 'idMeeting', 'idOrganiser', 'isEnd', 'objet', 'room', 'startTime', 'typeMedia', 'updatedAt'] as const
  $columns = MeetingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duree: number | null
  @column({ isPrimary: true })
  declare idMeeting: number
  @column()
  declare idOrganiser: number | null
  @column()
  declare isEnd: boolean | null
  @column()
  declare objet: string | null
  @column()
  declare room: string | null
  @column.dateTime()
  declare startTime: DateTime
  @column()
  declare typeMedia: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['content', 'conversationId', 'createdAt', 'isDeleted', 'isEdited', 'mediaUrl', 'msgId', 'readAt', 'replyToId', 'sendAt', 'senderId', 'status', 'type', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare content: string | null
  @column()
  declare conversationId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare isDeleted: boolean | null
  @column()
  declare isEdited: boolean | null
  @column()
  declare mediaUrl: string | null
  @column({ isPrimary: true })
  declare msgId: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare replyToId: bigint | number | null
  @column.dateTime()
  declare sendAt: DateTime
  @column()
  declare senderId: number | null
  @column()
  declare status: boolean | null
  @column()
  declare type: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ParticipantSchema extends BaseModel {
  static $columns = ['connecte', 'createdAt', 'duree', 'id', 'idMeeting', 'idParticipant', 'startTime', 'status', 'updatedAt'] as const
  $columns = ParticipantSchema.$columns
  @column()
  declare connecte: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duree: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idMeeting: number | null
  @column()
  declare idParticipant: number | null
  @column.dateTime()
  declare startTime: DateTime | null
  @column()
  declare status: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaySchema extends BaseModel {
  static $columns = ['createdAt', 'decalageHoraire', 'idPays', 'libelle', 'prefix', 'timeZone', 'updatedAt'] as const
  $columns = PaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare decalageHoraire: number | null
  @column({ isPrimary: true })
  declare idPays: number
  @column()
  declare libelle: string
  @column()
  declare prefix: string
  @column()
  declare timeZone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PreferredContactSchema extends BaseModel {
  static $columns = ['alanyaId', 'createdAt', 'idFriend', 'idPrefContact', 'updatedAt'] as const
  $columns = PreferredContactSchema.$columns
  @column()
  declare alanyaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare idFriend: number | null
  @column({ isPrimary: true })
  declare idPrefContact: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class StatusLikeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'statusId', 'updatedAt', 'userId'] as const
  $columns = StatusLikeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare statusId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class StatusViewSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'statusId', 'updatedAt', 'userId'] as const
  $columns = StatusViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare statusId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class StatutSchema extends BaseModel {
  static $columns = ['alanyaId', 'backgroundColor', 'createdAt', 'expiresAt', 'id', 'likedBy', 'mediaUrl', 'text', 'type', 'updatedAt', 'viewedBy'] as const
  $columns = StatutSchema.$columns
  @column()
  declare alanyaId: number | null
  @column()
  declare backgroundColor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare likedBy: number | null
  @column()
  declare mediaUrl: string | null
  @column()
  declare text: string | null
  @column()
  declare type: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viewedBy: number | null
}

export class UserAccessSchema extends BaseModel {
  static $columns = ['alanyaId', 'createdAt', 'dateLogin', 'device', 'idLogin', 'ipAdress', 'osSystem', 'updatedAt'] as const
  $columns = UserAccessSchema.$columns
  @column()
  declare alanyaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare dateLogin: DateTime
  @column()
  declare device: string | null
  @column({ isPrimary: true })
  declare idLogin: number
  @column()
  declare ipAdress: string | null
  @column()
  declare osSystem: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['alanyaId', 'alanyaPhone', 'avatarUrl', 'biometric', 'createdAt', 'deviceId', 'exclus', 'fcmToken', 'idPays', 'inCall', 'isOnline', 'lastSeen', 'nom', 'password', 'pseudo', 'typeCompte', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare alanyaId: number
  @column()
  declare alanyaPhone: string
  @column()
  declare avatarUrl: string | null
  @column()
  declare biometric: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string | null
  @column()
  declare exclus: boolean | null
  @column()
  declare fcmToken: string | null
  @column()
  declare idPays: number | null
  @column()
  declare inCall: boolean | null
  @column()
  declare isOnline: boolean | null
  @column.dateTime()
  declare lastSeen: DateTime | null
  @column()
  declare nom: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare pseudo: string
  @column()
  declare typeCompte: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
