/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Calls: () => import('#controllers/calls_controller'),
  Contacts: () => import('#controllers/contacts_controller'),
  Conversations: () => import('#controllers/conversations_controller'),
  Meetings: () => import('#controllers/meetings_controller'),
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Statuts: () => import('#controllers/statuts_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
